### ISSUE TITLE
Telstra貌似修复完毕

### ISSUE THREAD

**Issue by xlin084** [haha114514/No_Telstra_IPv6#1]
时间：05/12 17:45 AEDT

Telstra貌似已经修复
微信朋友圈没问题了，响应速度和ping也是正常了

不过还是多谢前两天救命之恩…

**Comment by haha114514** [comment]
是的，今天中午12点左右的时候已经修复好了。不过本项目还是保存在这里，因为QQ的问题还没有解决。
