### ISSUE TITLE
微信的问题现在解决了 

### ISSUE THREAD

**Issue by daniel-han-sydney** [haha114514/No_Telstra_IPv6#2]
亲测 微信的问题现在解决了 
gchat.qpic.cn  IPv6现在解析到AS134764  广东  
在Telstra上感觉跟IPv4一样了现在

**Comment by haha114514** [comment]
电信还是算了吧，可能关了v6直接访问v4香港的优化线路还是更香些，特别是上传图片的时候。不过这个gchat.qpic.cn是qq群用的，qq私聊和微信是其他的域名。你如果说的是微信或者Wechat流畅的话，倒还真和gchat.qpic.cn没关系。

**Comment by haha114514** [comment]
看了下，澳洲手机号注册的wechat的发图和接收图片以及朋友圈之类的域名是sgshort.wechat.com，根本就没有v6解析(而是2个新加坡腾讯云的IP）。结合之前12月 VIC出现的问题，本质是（在默认的Telstra.wap APN下，本机是只分配单栈v6的），当访问只有v4解析的域名时，Telstra的DNS64服务器给这些没有v6解析的域名解析指向他自家的v4 over v6的隧道，但是那一周这个隧道炸了，导致只有v4的域名业务无法访问。而切换到双栈APN Telstra.internet 并且只保留v4的话，就可以避免上面隧道爆炸的问题，以及一些奇奇怪怪的v6路由差的问题（比如qq群这个v4香港，v6大陆的操作）。

不过对于之前小红书上有些人从去年6月就开始有问题的情况，这个我就不清楚了。上面的分析只针对去年12月VIC的outage。

如果不是对v6有特殊需求，个人觉得平时直接关闭也好。
